- java/MatrixOperation.java
I would like to contribute to Java Section under Hacktoberfest 2023.
> Operations on Matrix in java

- python/valid_anagram.py
> valid_anagram is added to python

- c/Greatest number among five
Add c program "Find the greatest number among the 5 given numbers by user in c"
> Create Greatest number among five

- java/Rotating A Linked List.java
Add a java program "Rotating A Linked List"
> Create Rotating A Linked List.java

- python/display any message on heart.py
Add a program "display any message on heart"
> Create display any message on heart.py

- c++/sudoku_solver.cpp
- python/valid_anagram.py
> soduko_solver

- java/ReverseString.java
I attempted to write a code that reverses a string entered by the user. To achieve this, I utilized a string builder
> reverse a string

- javascript/Calculate-BMI.js
- javascript/Even-or-Odd.js
- javascript/MakeUpperCase.js
Added three JavaScript problems along with their solutions to enhance the repository's content and provide additional learning opportunities.
- Problem 1: Calculate-BMI.js
- Problem 2: Even-or-Odd.js
- Problem 3: MakeUpperCase.js
> Added 3 JavaScript problems with solution 

- c++/Sqrt_of_a_number.cpp
- c++/balanced_paranthesis.cpp
I have added 2 C++ Program
1) Sqrt of number using binary search
2) Balanced Paranthesis Problem
> Added 2 C++ Program 

- confirm password authentication
password confirmation program  that confirm the password .
> Create confirm password authentication

- javascript/LargestNumber.js
Wrote a javascript program to find the largest number among two different numbers
> Program To Find Largest Number

- c/paranthesisChecker.c
Created a file Paranthesis checker Code in C using stacks [Hacktober2023].
> Paranthesis Checker code.

- c++/BinarySearch.cpp
This is a program of binary search for an array  to search the index the of the element
> BinarySearch.cpp

- c++/Longest String Chain.cpp
> Create Longest String Chain.cpp

- c++/num_guessing_game.cpp
feature : the number guessing game program has been added in c++ directory.
> num-guessing-game added

- c++/InsertionSort.cpp
This is the program for Insertion Sort
in C++ language
> InsertionSort.cpp

- c/dectobin.c
Decimal to Binary Conversion program
> added dectobin.c program

- java/fibonacci.java
Thanks for viewing my pull request!
> first commit

- java/sort/RadixSorting.java
Add an implementation example of radix sort
> Add an implementation example of radix sort

- java/sort/QuickSort.java
Add an implementation example of quick sort
> Add an implementation example of quick sort

- java/sort/InsertSort.java
Add an implementation example of insert sort
> Add an implementation example of insert sort

- java/sort/MergeSort.java
- javascript/Even-or-Odd.js
Here we Use the Bit manipulation instead Modulo (%)  Operation This is Better Approach to Find the Odd & Even
> Add an Implementation Of Merge Sort & Well Explanation Using Comments

- c++/Container with Maximum Water.cpp
- c++/Minimum Sum Subarray Of Given Size.cpp
- c++/PrintKeypad.cpp
> CPP program added

- c++/SinglyC.cpp
Added Singly Circular Linked List Using C++ as an HacktoberFest-2023 Contribution.
> Added Singly Circular Linked List Using C++

- Jaggered Arrays
- Kadane's Algorithm
I have added Kadane's algorithm and Jaggered arrays code in C++.
> Added Kadane's algorithm and Jaggered arrays code in C++.

- java/Outer.java
Example of Inner class in java
> Java: Inner class

- bogosort.py
> added bogosort.py file

- python/snake_game.py
Fixes #146 
snake_game.py file can be run to play the snake game.
> feat: Added snake game in python folder

- c++/MajorityElement.cpp
Majority Element Issue Fulfilled
Please give me HacktoberFest Tag
Thanks
> Majority Elements

- java/Quick Sort Algorithm
-> Time complexity of this algorithm is on Average = O(n*Log(n)) , worst case = O(n *n) 
->Space complexity is linear O(1)
(in built sorting algorithm also uses recursive dual pivot quick sort for sorting because of its speed )
> Create Quick Sort Algorithm

- java/PalindromeChecker.java
I have added the code to check palindrome strings in Java.
Please approve my pull request @sherigar .
> Added PalindromeChecker.java

- c++/Sort_0_1_2.cpp
solves issue no #179 
pls review
> program for problem - Sort an array of 0s, 1s and 2s

- C/Insertion Sort Algorithm.c
[Fix]: issue #156  Insertion Sort Algorithm in C language
> Create Insertion Sort Algorithm.c

- c++/Container With Most Water.cpp
Kindly merge my contribution as I have solved the container with most water problem in C++ language successfully. Thank!@sherigar
Issue #154
> Create Container With Most Water.cpp

- python/treasure_island.py
Hi @sherigar, I have created treasure island game using python. It's very beginner friendly game which is created using if else statements. So kindly merge my pr with hacktoberfest accepted label. 
Thanks and Happy coding :)
> Treasure island

- c++/Container With Most Water.cpp
Hi there,
Changes made in new branch called: **MostWater-Container**
I'm added new two solutions for the Container with most water questions.
1. Recursive way
2. Two-pointer approach
please visit my github link and verify the my task which is assigned by you #154. If any issue with code let me know.
github: https://github.com/Hareesh061/HacktoberFest-2023/tree/MostWater-Container
> added new solutions for container with most water

- c++/Caesar_Cipher_Encoder_Decoder.cpp
The issue #203 was assigned to me. Here is the proposed PR for the same. Kindly add the hacktoberfest label. Thank you.
> Created Caesar_Cipher_Encoder_Decoder.cpp

- python/Calculator.py
@sherigar Could you please take a look at this pull request and merge it, I've proposed adding the "Calculator Program in Python" project to the repository. Your feedback and review would be greatly appreciated.
Fixes #208
> Add Calculator Program in Python 

- python/pong game/ball.py
- python/pong game/main.py
- python/pong game/paddle.py
- python/pong game/scoreboard.py
It is a Python Pong Game which is created using turtle library python. Pong is a two-dimensional sports game that simulates table tennis. The player controls an in-game paddle by moving it vertically across the left or right side of the screen. They can compete against another player controlling a second paddle on the opposing side. Players use the paddles to hit a ball back and forth. Paddle's movement is done with up-down arrow key for one player, and "w"&"s" key for another player to move the paddle up and down respectively.
> Pong game in Python

- insertalgo.py
- maxnum.cpp
> Insertion sort and maxm value in array in cpp

- python/url_shortener.py
Added URL Shortener Project which allows users to shorten the long URLs using the 'pyshorteners' library
> url_shortener

- java/MergeSortAlgo.java
Hello @sherigar 
I have added Merge Sort Algorithm in Java to the java folder
Please let me know if any difficulties in merging.
Thank you.
> Adding Merge sort Algorithm in Java

- Remove Nth Node from end of list problem..java
> Create Remove Nth Node from end of list problem..java

- c++/Kaprekar.cpp
> Implementation of C++ Program to Check Kaprekar Number for Specific Base

- java/BogoSort.java
> add BogoSort java

- Treasure Island game.py
> Update Treasure Island game.py
